import test from 'node:test';import assert from 'node:assert/strict';import {renderPartnerEngagementEmail as render} from '../functions/lib/partner-engagement-email.mjs';
const request={id:'request-example',cleaningType:'Limpeza regular',place:'Lisboa',postalCode:'1000',typology:'Apartamento T2',frequency:'Semanal',when:'A combinar',day:'Segunda-feira',period:'Manhã',remaining:3,obtained:0,registrationConfirmed:true};
const payload={event_id:'engagement:test:example',event_type:'request_digest',partner_name:'Parceiro exemplo',dashboard_url:'https://parceiros.guiadoproprietario.pt/?t=PERSONAL',data:{copyVersion:'v2',prices:{partilhada:280,exclusiva:500},freeContacts:0,requests:[request],request,registrationConfirmationReady:true,whatsappReady:false,total:1}};
test('V2 event adapter renders six digest cards, preserves personal links and hides client data',()=>{const p={...payload,data:{...payload.data,total:8,requests:Array(6).fill({...request,client_name:'SECRET',client_phone:'SECRET'})}};const e=render(p);assert.equal((e.html.match(/class="request-cta"/g)||[]).length,6);assert.match(e.text,/Ver mais 2 pedidos/);assert.doesNotMatch(e.html,/SECRET/);assert.match(e.text,/t=PERSONAL/);});
test('V2 acquired contact and stop notice use exact request identity and verified credit',()=>{const e=render({...payload,event_type:'contact_accepted',data:{...payload.data,contactAcquired:true,modality:'exclusiva',client_name:'Ana exemplo',client_phone:'910000000',postal_code:'1000-001'}});assert.match(e.subject,/REQUES/);assert.match(e.text,/Só você recebe este contacto através do Guia do Proprietário\./);assert.doesNotMatch(e.text,/enquanto.*exclusividade/);assert.throws(()=>render({...payload,event_type:'contact_accepted',data:{...payload.data,kind:'client_stop',contactType:'partilhado',rightGranted:false}}));});
test('V2 client action retains signed client link and never leaks partner access',()=>{const e=render({...payload,event_type:'contact_accepted',data:{copyVersion:'v2',audience:'client',modality:'partilhada',client_name:'Ana exemplo',municipality:'Lisboa',professional_name:'Empresa exemplo',professional_phone:'910000000',resolve_url:'https://parceiros.guiadoproprietario.pt/pedido-resposta.html#token=SIGNED',stop_url:'https://parceiros.guiadoproprietario.pt/pedido-contactos.html#token=SIGNED'}});assert.match(e.text,/Já resolveu a limpeza/);assert.doesNotMatch(e.html,/PERSONAL/);});

test('workflow adapter renders warranty confirmations and signed customer questions without partner credentials',()=>{const answer='https://parceiros.guiadoproprietario.pt/pedido-resposta.html?t=SIGNED';const c=render({...payload,event_type:'C5',dashboard_url:'',data:{copyVersion:'v2',workflowKind:'C5',specificProfessional:false,name:'Ana exemplo',place:'Lisboa',responses:{yes:answer+'&resposta=sim',no:answer+'&resposta=nao'}}});assert.match(c.text,/algum profissional/i);assert.doesNotMatch(c.text,/PERSONAL/);const g=render({...payload,event_type:'P10',data:{...payload.data,workflowKind:'P10',rightGranted:true,contactType:'partilhado'}});assert.match(g.text,/Não expira/);});


import {renderEmailRequestCard as card} from '../functions/lib/partner-email-copy-v2.mjs';
const r={id:'7f3k2a-example',cleaningType:'Limpeza regular',place:'Lisboa',postalCode:'1000-001',typology:'Apartamento T2',frequency:'Semanal',when:'A combinar',day:'segunda-feira',period:'manhã',remaining:3,obtained:0,registrationConfirmed:true,whatsappVerified:true,interestConfirmed:true,client_name:'PRIVATE-NAME',client_phone:'PRIVATE-PHONE',client_email:'private@example.invalid'};
const d={name:'Parceiro <exemplo>',url:'https://parceiros.guiadoproprietario.pt/?t=PERSONAL',prices:{partilhada:280,exclusiva:500},freeContacts:0,requests:[r],registrationConfirmationReady:true,whatsappReady:true,model:'novo',total:1};
test('request card leads with service and locality and explains timing and available free entitlement',()=>{
 const c=card(r,{...d,freeContacts:2});
 for(const format of ['html','text']){assert.ok(c[format].indexOf('Limpeza regular')<c[format].indexOf('Lisboa (1000)'));assert.ok(c[format].indexOf('Lisboa (1000)')<c[format].indexOf('Pedido confirmado'));}
 assert.match(c.text,/Dia: segunda-feira/);assert.match(c.text,/Horário: manhã/);assert.doesNotMatch(c.text,/prefere segunda-feira, manhã/);assert.match(c.text,/Pode usar 1 contacto partilhado grátis da sua conta neste pedido/);
 assert.match(card(r,{...d,freeSharedContacts:0,freeExclusiveContacts:1}).text,/1 contacto exclusivo grátis/);
 assert.doesNotMatch(card({...r,obtained:1,remaining:2},{...d,freeSharedContacts:0,freeExclusiveContacts:1}).text,/GRÁTIS|Pode usar/);
 assert.doesNotMatch(card(r,{...d,freeContacts:2},{candidate:true}).text,/GRÁTIS|Pode usar/);
});
